"""company table

Revision ID: d711b548b06c
Revises: aa63bc2612bf
Create Date: 2020-05-05 00:19:21.914788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd711b548b06c'
down_revision = 'aa63bc2612bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('companyName', sa.String(length=64), nullable=True),
    sa.Column('logoCompany', sa.LargeBinary(), nullable=True),
    sa.Column('tagLine', sa.String(length=64), nullable=True),
    sa.Column('foreword', sa.String(length=256), nullable=True),
    sa.Column('aboutUs', sa.String(length=256), nullable=True),
    sa.Column('workWithUs', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_companyName'), 'company', ['companyName'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_companyName'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
